name: "Setup tools"
description: "Setup tools with aqua"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # 3.1.0
      with:
        aqua_version: v2.44.1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
